export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}



export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor:"blue",
          padding:"1rem",
          
        }}>
         <h1>Header</h1>
          </header>
        {children}
        <footer style={{
          backgroundColor:"red",
          padding:"1rem",
          
        }}>
         <h1>Footer</h1>
          </footer>
      </body>
    </html>
  )
}
